name       : bzr
version    : 2.7.0
release    : 7
source     :
    - https://launchpad.net/bzr/2.7/2.7.0/+download/bzr-2.7.0.tar.gz : 0d451227b705a0dd21d8408353fe7e44d3a5069e6c4c26e5f146f1314b8fdab3
homepage   : http://bazaar.canonical.com
license    : GPL-2.0
component  : programming.tools
summary    : Bazaar Version Control System
description: |
    Bazaar is a version control system that helps track project history over time and to collaborate easily with others. It runs on a variety of operating systems and is used heavily by Ubuntu.
build      : |
    %python_setup
    python setup.py build
install    : |
    %python_install

