name        : bzr
version     : 2.6.0
release     : 3
source      :
    - https://launchpad.net/bzr/2.6/2.6.0/+download/bzr-2.6.0.tar.gz : 0994797182eb828867eee81cccc79480bd2946c99304266bc427b902cf91dab0
homepage    : http://bazaar.canonical.com
license     :
    - GPL-2.0
summary     : Bazaar Version Control System
description : |
    Bazaar is a version control system that helps track project history over time and to collaborate easily with others. It runs on a variety of operating systems and is used heavily by Ubuntu.
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
